# Generated by Django 3.1.4 on 2020-12-07 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('city', models.CharField(choices=[('surat', 'surat'), ('bharuch', 'bharuch'), ('navsari', 'navsari'), ('valsad', 'valsad')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MapTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(choices=[('room', 'room'), ('bike', 'bike'), ('car', 'car')], max_length=20, null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('to_date', models.DateField(null=True)),
                ('description', models.TextField(null=True)),
                ('photo', models.ImageField(null=True, upload_to='owner/')),
                ('price', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(choices=[('surat', 'surat'), ('bharuch', 'bharuch'), ('navsari', 'navsari'), ('valsad', 'valsad')], max_length=20, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booknow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('from_date', models.DateTimeField(null=True)),
                ('to_date', models.DateTimeField(null=True)),
                ('pay_status', models.CharField(choices=[('successfull', 'successfull'), ('unsuccessfull', 'unsuccessfull')], max_length=20, null=True)),
                ('booked_days', models.IntegerField(null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('tools', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='tools.maptool')),
            ],
        ),
    ]
