# Generated by Django 3.1.4 on 2020-12-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booknow',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
