# Generated by Django 3.1.4 on 2020-12-08 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_booknow_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booknow',
            name='pay_status',
            field=models.CharField(choices=[('successful', 'successful'), ('unsuccessful', 'unsuccessful')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20, null=True)),
                ('pay', models.IntegerField(null=True)),
                ('txnid', models.CharField(max_length=50, null=True)),
                ('banktxnid', models.IntegerField(null=True)),
                ('txndate', models.CharField(max_length=20, null=True)),
                ('orderid', models.CharField(max_length=20, null=True)),
                ('booknow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booknow', to='tools.booknow')),
            ],
        ),
    ]
