# Generated by Django 3.1.4 on 2020-12-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_auto_20201208_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booknow',
            name='from_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='booknow',
            name='to_date',
            field=models.DateField(null=True),
        ),
    ]
