# Generated by Django 3.1.4 on 2020-12-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_auto_20201208_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='maptool',
            name='Adults',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='maptool',
            name='Children',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
