# Generated by Django 3.1.4 on 2020-12-09 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_auto_20201209_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maptool',
            name='Adults',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='maptool',
            name='Children',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
