# Generated by Django 3.1.4 on 2020-12-09 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_auto_20201209_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maptool',
            name='Adults',
        ),
        migrations.RemoveField(
            model_name='maptool',
            name='Children',
        ),
    ]
