# Generated by Django 3.1.4 on 2020-12-09 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0008_auto_20201209_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiplePhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo1', models.ImageField(null=True, upload_to='owner/multi/')),
                ('photo2', models.ImageField(null=True, upload_to='owner/multi/')),
                ('photo3', models.ImageField(null=True, upload_to='owner/multi/')),
                ('photo4', models.ImageField(null=True, upload_to='owner/multi/')),
                ('maptools', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tools.maptool')),
            ],
        ),
    ]
