# Generated by Django 3.1.4 on 2020-12-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0010_save_tools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maptool',
            name='to_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
