# Generated by Django 3.1.4 on 2020-12-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0012_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='review',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
