# Generated by Django 3.1.4 on 2020-12-10 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0013_rating_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('from_date', models.DateField(null=True)),
                ('to_date', models.DateField(null=True)),
                ('pay_status', models.CharField(choices=[('success', 'success'), ('pending', 'pending')], max_length=20, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('booked_days', models.IntegerField(null=True)),
                ('booking_id', models.CharField(max_length=20, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(choices=[('room', 'room'), ('bike', 'bike'), ('car', 'car')], max_length=20, null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('to_date', models.DateField(auto_now_add=True, null=True)),
                ('description', models.TextField(null=True)),
                ('photo', models.ImageField(null=True, upload_to='owner/')),
                ('price', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(choices=[('surat', 'surat'), ('bharuch', 'bharuch'), ('navsari', 'navsari'), ('valsad', 'valsad')], max_length=20, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='maptool',
            name='owner',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='banktxnid',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='pay',
            new_name='bank_txn_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='orderid',
            new_name='payment_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='txndate',
            new_name='txn_date',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='txnid',
            new_name='txn_id',
        ),
        migrations.RemoveField(
            model_name='multiplephotos',
            name='maptools',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='booknow',
        ),
        migrations.RemoveField(
            model_name='save_tools',
            name='tools',
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('pending', 'pending')], default='pending', max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Booknow',
        ),
        migrations.DeleteModel(
            name='MapTool',
        ),
        migrations.AddField(
            model_name='booking',
            name='tools',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='tools.tool'),
        ),
        migrations.AddField(
            model_name='multiplephotos',
            name='tool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tools.tool'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tools.booking'),
        ),
        migrations.AddField(
            model_name='save_tools',
            name='tool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tools.tool'),
        ),
    ]
