# Generated by Django 3.1.4 on 2020-12-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0014_auto_20201210_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
