# Generated by Django 3.1.4 on 2020-12-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0015_tool_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pay_status',
            field=models.CharField(default='pending', max_length=20, null=True),
        ),
    ]
