# Generated by Django 3.1.4 on 2020-12-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0016_auto_20201211_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='bank_txn_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='txn_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
