# Generated by Django 3.1.4 on 2020-12-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0017_auto_20201216_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='txn_date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
